// User-manual CONTENT (bilingual). The PDF generator (manualPdf.ts) renders
// whatever this module returns, so the manual always ships in the language the
// user already selected and stays in one place to update alongside features.
// Long prose lives here rather than i18n.ts (same convention as HelpView).

import type { Lang } from "./i18n";

export interface ManualSection {
  title: string;
  intro: string; // one short paragraph
  steps?: string[]; // numbered how-to
  example?: string; // a concrete worked example
  tips?: string[]; // bullet advice
}

export interface ManualContent {
  title: string;
  subtitle: string;
  generatedNote: string; // "Generated by … v{version} — {date}"
  tocTitle: string;
  exampleLabel: string;
  tipsLabel: string;
  stepsLabel: string;
  footer: string;
  sections: ManualSection[];
}

const EN: Omit<ManualContent, "generatedNote"> = {
  title: "Pigment Match",
  subtitle: "User manual — from a color to a real oil-paint mixture",
  tocTitle: "Contents",
  exampleLabel: "Example",
  tipsLabel: "Tips",
  stepsLabel: "How to",
  footer: "Pigment Match — user manual",
  sections: [
    {
      title: "What Pigment Match does",
      intro:
        "Pigment Match turns a target color (a HEX code, a pixel from a photo, a color picked on screen) into an approximate mixing recipe using YOUR palette of real oil pigments, and describes color the way painters talk: value, temperature, saturation and hue. Everything runs in your browser — no account, no server; your data stays on your device.",
      tips: [
        "Recipes are strong starting points, not lab formulas: pigment data is estimated. The Calibrate tab teaches the app your real tubes and improves everything.",
        "The app works offline once loaded (installable PWA). Only the optional cloud AI and cloud sync need a connection.",
      ],
    },
    {
      title: "Match — from color to recipe",
      intro:
        "The home tab. Set a target color with the picker, a HEX/RGB value, or the Screen button (Chromium browsers) that picks a color from anywhere on your monitor. The recipe card shows the pigments and their proportions, the predicted mixed color, and two honesty scores: Match % (overall closeness, ΔE2000) and Value (how close the lightness is — often what matters most).",
      steps: [
        "Enter the target color (picker, HEX, RGB or Screen).",
        "Read the recipe: proportions as parts (2 : 1 : trace) or %, switchable.",
        "Toggle Simple (fewer practical pigments) vs Precise (squeezes the last ΔE).",
        "Optionally set an amount (“Make 20 ml”) to get real quantities per pigment.",
        "Use “Save to Logbook” to keep a recipe you liked.",
      ],
      example:
        "Target #927073 (a muted rose-grey): with the default palette the app suggests ~5 parts Titanium White, 2 parts Cadmium Red Light, 1 part Ultramarine, a touch of Yellow Ochre — match 99%. Mix the parts with a consistent scoop (a knife-tip per part).",
      tips: [
        "A recipe almost never collapses to a single tube: real colors are mixes. If it does, your target essentially IS that pigment.",
        "Must-use tubes: when you already know your base (“this skin starts from Pale Rose Blush greyed with Raw Umber”), pin those tubes above the recipe and the mix is built around them — in any engine.",
        "Mixing engines: Classic (default), Spectral (experimental, full-spectrum) and 2-const (uses opacity). Stay on Classic unless you're curious.",
        "Max colors, Value-first and Golden ratio are optional constraints under the recipe — the shown score always reflects what's displayed.",
      ],
    },
    {
      title: "Color string — the premixed value scale",
      intro:
        "Under every recipe, the Color string card shows the light→shadow scale of the base mix: three lighter steps (adding your white) and three darker steps (adding an in-family dark pigment — an earth for skin, never black by default). Each step shows its value (L*) and, when clicked, its full proportions.",
      example:
        "For a skin base, the shadow steps add Burnt Umber at 8 / 18 / 30% — the color stays warm instead of greying. Use the “Darken with” dropdown to try Ultramarine for a cooler shadow line.",
      tips: [
        "Premix these puddles before a session and you'll never chase a value mid-stroke.",
      ],
    },
    {
      title: "Variations, harmonies and the gamut map",
      intro:
        "Every target comes with six painterly variations (lighter, darker, warmer, cooler, more/less saturated — saturation changes keep the value) and five color-wheel harmonies, each with its own “How to mix it” recipe. When a match is poor, an amber note suggests the one library tube that would close the gap, and the gamut map draws your pigments on the hue/chroma plane so you can SEE why the target is out of reach.",
      tips: [
        "“Less saturated” greys the color at the same value — the right tool when a skin tone matches but reads too colorful.",
        "In the gamut map, mixes can only land inside the shaded hull. A target outside it needs a new tube, not more mixing.",
      ],
    },
    {
      title: "Image — sample colors from a photo",
      intro:
        "Upload a photo (or use the camera) and click to pick colors. Zoom and pan for precision, use the loupe for pixel work, set a brush radius to average an area, and enable Average mode to combine several clicks with a spread readout. The white-balance reference cancels your phone camera's color cast.",
      steps: [
        "Put a white or grey card (plain printer paper works) next to your subject, in the same light, and photograph both together.",
        "Click “White balance”, then click the card in the photo.",
        "Pick your colors — every pick is corrected against the card. “Keep value” corrects only the tint and preserves lightness.",
        "For noisy photos, turn on Average and click 3–5 spots of the same area.",
      ],
      example:
        "Photographing a painted swatch under a warm lamp: without white balance the sample reads orange-ish; after clicking the paper card, the cast is removed and the recipe matches the paint, not the lamp.",
      tips: [
        "The simultaneous-contrast card shows your sampled color inside its real surround vs on white/grey — the same color reads differently, so judge mixes against their neighbors.",
        "Colors from phone photos are relative, not absolute. Value and temperature relationships survive the camera; exact hue may not.",
      ],
    },
    {
      title: "Extract — a palette from any image",
      intro:
        "Extract pulls the 4–20 dominant colors of an image, each with its own recipe and a painter description. Drag a box to limit extraction to an area (or Invert it to exclude a background). The Color map view posterizes the image to the extracted palette. Below, the Value study reduces the image to 3–5 value planes — the notan — with a mixing recipe per plane.",
      example:
        "Load a landscape reference, extract 8 colors, then open “What tubes do I need?”: the planner picks the smallest set of library tubes that can mix all of them, and “Use these tubes” creates that palette instantly.",
      tips: [
        "Start paintings from the value study: get the 3–4 big masses right and the details will sit on solid ground.",
      ],
    },
    {
      title: "Scene — advice in context",
      intro:
        "Scene mode analyzes a zone RELATIVE to the whole image. It profiles the scene's light (warm or cool light, high or low key), classifies your dragged zone as light / halftone / shadow, and gives relational advice — e.g. in a warm-light scene, a shadow that reads warm gets “cool it with ~3% Ultramarine”, with the measured and scene-adjusted recipes side by side.",
      tips: [
        "The scene profile is computed once from the whole photo on purpose: zones are judged against the scene, not against themselves.",
        "If the photo misleads (indoor warm bulb but you want cool light), use “flip light” to invert the interpretation.",
      ],
    },
    {
      title: "Coach — how to correct a mix",
      intro:
        "Give the Coach the target and your current mix (typed or sampled from a photo of your palette) and it acts like a teacher behind you: lift the value, cool it a touch, mute it with the complement — always naming actual pigments from your palette. The “How much, exactly?” card quantifies the best single addition.",
      example:
        "Target skin tone vs your puddle: “Add 1 part Ultramarine for every 12 parts of your puddle” — or in ml/g/drops if you tell it your puddle size. It also predicts the match after the addition.",
      tips: [
        "Add in 2–3 small steps and re-sample. Strong pigments (phthalos, dioxazine) go much further than you think.",
      ],
    },
    {
      title: "Mix — two-photo check",
      intro:
        "A focused cousin of the Coach: sample the TARGET from a reference photo and the ACTUAL paint from a photo of your palette mix. You get both painter descriptions, a value scale with both marked (and the ΔL between them), and the Coach's advice with a match %.",
    },
    {
      title: "Compare — reference vs work-in-progress",
      intro:
        "Upload the reference and a photo of your painting, align each with four draggable corners (de-keystoning), then critique: swipe/onion-skin overlay with a squint blur, value views (greyscale, notan, difference heatmap, histogram), color-difference maps (ΔE, temperature, saturation, hue), click-a-region coaching, side-by-side palette extraction, and a scorecard with plain-language conclusions.",
      tips: [
        "Trust the VALUE comparisons most — they survive photo conditions best.",
        "“Normalize lighting” removes global exposure/WB differences between the two photos before comparing.",
      ],
    },
    {
      title: "IMG Lab — prepare images",
      intro:
        "A dedicated image workshop: exposure/contrast/saturation/temperature adjustments (live), an Oil painting filter that simplifies the photo into flat paint-like daubs with crisp edges (Classic, or the GPU Anisotropic mode where strokes follow the forms), a pack of extra filters (watercolor smoothing, Lab value posterize, XDoG ink lines, CLAHE exposure recovery, lighting flattening, impasto relief), a Stencil mode for clean traceable line art, and optional AI enhancement. Everything but the AI is local and deterministic.",
      steps: [
        "Adjust first (contrast feeds the filters).",
        "Turn on Oil painting for the “already painted” reference look; add Impasto relief on top for paint thickness.",
        "Or pick one of the extra filters: CLAHE / lighting flattening fix a bad exposure; posterize gives value bands; XDoG or Stencil give line art.",
        "Download as PNG and use it as reference in Extract, Scene or Compare.",
      ],
      tips: [
        "Oil + Stencil = line art of the SIMPLIFIED shapes — great for transferring a drawing.",
        "AI enhancement can shift colors — sample from the original when accuracy matters.",
      ],
    },
    {
      title: "Logbook — your mixing notebook",
      intro:
        "A painter's notebook organized in projects: each project holds a reference photo, a finished-painting photo, and color entries (name, recipe text, notes, a swatch chip you can sample from an uploaded swatch photo). Export a project as an elegant PDF, or back up everything as a single JSON file (photos included) and import it elsewhere.",
      tips: [
        "Photos are stored in your browser's IndexedDB — large quota, but per-browser. Export regularly if the machine is shared.",
      ],
    },
    {
      title: "Calibrate — teach the app your real tubes",
      intro:
        "Pigment data ships as informed estimates. Calibration fits the model to YOUR paints: record observations (“I mixed these parts and got THIS color”) and press Calibrate. The fastest path is the calibration chart: print the PDF grid, paint every patch with the labeled tube, photograph the sheet, align the border corners, and the app reads every patch in one pass — auto white-balanced against the blank paper cell.",
      steps: [
        "Download the chart (PDF) from the Calibrate tab and print it (cardstock, or paper glued to board; seal with clear medium if you like).",
        "Paint each patch thick and opaque; tints are 1 part pigment + 3 parts white. Leave PAPER blank.",
        "Photograph the sheet flat in even daylight, no glare; upload the photo and drag the 4 handles to the bold border's corners.",
        "“Read the chart”, check the color chips look right, “Add observations”.",
        "Press Calibrate (tick “also fit color” if you painted carefully) and enable the calibrated model with the toggle at the top.",
      ],
      tips: [
        "Re-reading a chart skips exact duplicates automatically and asks you what to do when a mix was recorded with a different color.",
        "The suggested-mixes chips propose the most informative next observations if you prefer recording mixes one by one.",
      ],
    },
    {
      title: "Palette — your real tubes",
      intro:
        "Create palettes, add pigments by hand or from the built-in library (Traditional Oil, Winsor & Newton Artists', Winton, W&N Mixed, Corfix), and edit each tube: masstone color (typed or sampled from a photo of a swatch), optional undertone, opacity, temperature and tinting strength. The availability checkbox excludes a tube from recipes without deleting it. The Tube substitute tool mixes a ran-out tube from the rest and names the closest single tube to buy.",
      tips: [
        "Export/import palettes as JSON — the file carries the palette's calibration too, so a backup restores your full working state.",
        "Share a palette by link or QR code from the Share button.",
      ],
    },
    {
      title: "Settings, language and cloud sync",
      intro:
        "Settings holds the language (English/Spanish — the app never lets the browser auto-translate it), the active palette, default recipe options, your optional Gemini API key, and the optional cloud sync. Sync is bring-your-own Firebase: paste your own free project's config, sign in with Google, and the app pulls on open and auto-pushes changes — palettes, settings, logbook text, and the active images. It's off by default; without it the app is 100% local.",
      tips: [
        "Install the app (Add to Home Screen / Install) for offline use and a share-target: send a photo from your phone's share sheet straight into the Image tab.",
      ],
    },
    {
      title: "Getting accurate color from photos — the golden rules",
      intro:
        "Phone cameras auto-correct everything, so treat photo color as relative, not absolute. These habits remove most of the error.",
      steps: [
        "Always include a white/grey card in the shot and use the white-balance reference.",
        "Photograph flat, in even indirect daylight, avoiding glare on wet paint.",
        "Average several picks (or use a bigger brush) — single pixels are noisy, especially in darks.",
        "Judge relationships (lighter/darker, warmer/cooler) rather than absolute hex values.",
        "Calibrate your palette: it corrects the model where it matters, per YOUR tubes.",
      ],
    },
  ],
};

const ES: Omit<ManualContent, "generatedNote"> = {
  title: "Pigment Match",
  subtitle: "Manual de usuario — de un color a una mezcla real de óleo",
  tocTitle: "Contenido",
  exampleLabel: "Ejemplo",
  tipsLabel: "Consejos",
  stepsLabel: "Cómo hacerlo",
  footer: "Pigment Match — manual de usuario",
  sections: [
    {
      title: "Qué hace Pigment Match",
      intro:
        "Pigment Match convierte un color objetivo (un HEX, un píxel de una foto, un color tomado de la pantalla) en una receta de mezcla aproximada usando TU paleta de pigmentos reales al óleo, y describe el color como hablan los pintores: valor, temperatura, saturación y matiz. Todo corre en tu navegador — sin cuenta ni servidor; tus datos quedan en tu dispositivo.",
      tips: [
        "Las recetas son buenos puntos de partida, no fórmulas de laboratorio: los datos de pigmentos son estimados. La pestaña Calibrar le enseña a la app tus tubos reales y mejora todo.",
        "La app funciona sin conexión una vez cargada (PWA instalable). Solo la IA en la nube y el sync opcional necesitan internet.",
      ],
    },
    {
      title: "Match — del color a la receta",
      intro:
        "La pestaña principal. Fijá el color objetivo con el selector, un valor HEX/RGB, o el botón Pantalla (navegadores Chromium) que toma un color de cualquier parte del monitor. La tarjeta de receta muestra los pigmentos y sus proporciones, el color mezclado previsto y dos puntajes honestos: Match % (cercanía total, ΔE2000) y Valor (qué tan cerca está la luminosidad — a menudo lo más importante).",
      steps: [
        "Ingresá el color objetivo (selector, HEX, RGB o Pantalla).",
        "Leé la receta: proporciones en partes (2 : 1 : toque) o %, conmutable.",
        "Alterná Simple (pocos pigmentos prácticos) vs Preciso (exprime el último ΔE).",
        "Opcional: fijá una cantidad (“Hacer 20 ml”) para obtener cantidades reales por pigmento.",
        "Usá “Guardar en Bitácora” para conservar una receta que te gustó.",
      ],
      example:
        "Objetivo #927073 (un rosa grisáceo apagado): con la paleta por defecto la app sugiere ~5 partes de Blanco Titanio, 2 de Rojo Cadmio Claro, 1 de Ultramar y un toque de Ocre Amarillo — match 99%. Medí las partes con una medida constante (una punta de espátula por parte).",
      tips: [
        "Una receta casi nunca colapsa a un solo tubo: los colores reales son mezclas. Si pasa, tu objetivo prácticamente ES ese pigmento.",
        "Tubos obligatorios: cuando ya conocés tu base (“esta piel arranca de Pale Rose Blush agrisada con Raw Umber”), fijá esos tubos arriba de la receta y la mezcla se construye alrededor de ellos — en cualquier motor.",
        "Motores de mezcla: Classic (por defecto), Spectral (experimental, espectro completo) y 2-const (usa la opacidad). Quedate en Classic salvo curiosidad.",
        "Máx. colores, Priorizar valor y Proporción áurea son restricciones opcionales bajo la receta — el puntaje mostrado siempre refleja lo que se muestra.",
      ],
    },
    {
      title: "Escala de valor (color string)",
      intro:
        "Bajo cada receta, la tarjeta de escala de valor muestra la escala luz→sombra de la mezcla base: tres pasos más claros (agregando tu blanco) y tres más oscuros (agregando un pigmento oscuro de la misma familia — una tierra para la piel, nunca negro por defecto). Cada paso muestra su valor (L*) y, al hacer clic, sus proporciones completas.",
      example:
        "Para una base de piel, los pasos de sombra agregan Tierra Sombra Tostada al 8 / 18 / 30% — el color se mantiene cálido en vez de engrisarse. Con el selector “Oscurecer con” probá Ultramar para una línea de sombra más fría.",
      tips: [
        "Premezclá estos montoncitos antes de la sesión y no vas a perseguir un valor a mitad de pincelada.",
      ],
    },
    {
      title: "Variaciones, armonías y mapa de gamut",
      intro:
        "Cada objetivo viene con seis variaciones de pintor (más claro, más oscuro, más cálido, más frío, más/menos saturado — los cambios de saturación conservan el valor) y cinco armonías de círculo cromático, cada una con su receta “Cómo mezclarla”. Cuando un match da bajo, una nota ámbar sugiere el tubo de la librería que más cerraría la brecha, y el mapa de gamut dibuja tus pigmentos en el plano matiz/croma para que VEAS por qué el objetivo está fuera de alcance.",
      tips: [
        "“Menos saturado” engrisa el color al mismo valor — la herramienta justa cuando un tono de piel matchea pero se ve demasiado colorido.",
        "En el mapa de gamut, las mezclas solo caen dentro del casco sombreado. Un objetivo afuera necesita un tubo nuevo, no más mezcla.",
      ],
    },
    {
      title: "Imagen — muestrear colores de una foto",
      intro:
        "Subí una foto (o usá la cámara) y hacé clic para tomar colores. Zoom y paneo para precisión, lupa para trabajo de píxel, radio de pincel para promediar un área, y modo Promediar para combinar varios clics con lectura de dispersión. La referencia de balance de blancos cancela el tinte de la cámara del teléfono.",
      steps: [
        "Poné una tarjeta blanca o gris (sirve papel de impresora) al lado del objeto, con la misma luz, y fotografiá ambos juntos.",
        "Tocá “Balance de blancos” y hacé clic en la tarjeta dentro de la foto.",
        "Tomá tus colores — cada muestra se corrige contra la tarjeta. “Conservar valor” corrige solo el tinte y mantiene la luminosidad.",
        "Con fotos ruidosas, activá Promediar y hacé clic en 3–5 puntos de la misma zona.",
      ],
      example:
        "Fotografiando un swatch pintado bajo una lámpara cálida: sin balance de blancos la muestra sale anaranjada; tras el clic en la tarjeta, el tinte desaparece y la receta corresponde a la pintura, no a la lámpara.",
      tips: [
        "La tarjeta de contraste simultáneo muestra tu color muestreado dentro de su entorno real vs sobre blanco/gris — el mismo color se lee distinto, así que juzgá las mezclas contra sus vecinos.",
        "Los colores de fotos de celular son relativos, no absolutos. Las relaciones de valor y temperatura sobreviven a la cámara; el matiz exacto puede que no.",
      ],
    },
    {
      title: "Extraer — una paleta de cualquier imagen",
      intro:
        "Extraer saca los 4–20 colores dominantes de una imagen, cada uno con su receta y descripción de pintor. Arrastrá un recuadro para limitar la extracción a un área (o Invertí para excluir un fondo). La vista Mapa de color posteriza la imagen a la paleta extraída. Debajo, el Estudio de valores reduce la imagen a 3–5 planos de valor — el notan — con receta por plano.",
      example:
        "Cargá una referencia de paisaje, extraé 8 colores y abrí “¿Qué tubos necesito?”: el planificador elige el conjunto mínimo de tubos de la librería que puede mezclarlos todos, y “Usar estos tubos” crea esa paleta al instante.",
      tips: [
        "Empezá los cuadros por el estudio de valores: con las 3–4 grandes masas bien puestas, los detalles se asientan sobre terreno firme.",
      ],
    },
    {
      title: "Escena — consejo en contexto",
      intro:
        "El modo Escena analiza una zona EN RELACIÓN a la imagen completa. Perfila la luz de la escena (luz cálida o fría, clave alta o baja), clasifica tu zona como luz / medio tono / sombra, y da consejo relacional — p. ej. en una escena de luz cálida, una sombra que se lee cálida recibe “enfriala con ~3% de Ultramar”, con las recetas medida y ajustada a la escena lado a lado.",
      tips: [
        "El perfil de escena se calcula una sola vez de toda la foto, a propósito: las zonas se juzgan contra la escena, no contra sí mismas.",
        "Si la foto engaña (lámpara cálida interior pero querés luz fría), usá “invertir luz” para dar vuelta la interpretación.",
      ],
    },
    {
      title: "Coach — cómo corregir una mezcla",
      intro:
        "Dale al Coach el objetivo y tu mezcla actual (tipeada o muestreada de una foto de tu paleta) y actúa como un maestro detrás tuyo: subí el valor, enfriala un toque, apagala con el complemento — siempre nombrando pigmentos reales de tu paleta. La tarjeta “¿Cuánto exactamente?” cuantifica la mejor adición única.",
      example:
        "Tono de piel objetivo vs tu montón: “Agregá 1 parte de Ultramar por cada 12 partes de tu montón” — o en ml/g/gotas si le decís el tamaño del montón. También predice el match después del agregado.",
      tips: [
        "Agregá en 2–3 pasos chicos y volvé a muestrear. Los pigmentos fuertes (ftalos, dioxazina) rinden mucho más de lo que pensás.",
      ],
    },
    {
      title: "Mezcla — chequeo con dos fotos",
      intro:
        "Un primo enfocado del Coach: muestreá el OBJETIVO de una foto de referencia y la PINTURA REAL de una foto de tu mezcla en la paleta. Obtenés ambas descripciones de pintor, una escala de valor con los dos marcados (y el ΔL entre ellos), y el consejo del Coach con su match %.",
    },
    {
      title: "Comparar — referencia vs obra en progreso",
      intro:
        "Subí la referencia y una foto de tu cuadro, alineá cada una con cuatro esquinas arrastrables (corrección de perspectiva), y criticá: superposición con barrido/piel de cebolla y desenfoque de entrecerrar los ojos, vistas de valor (grises, notan, mapa de diferencias, histograma), mapas de diferencia de color (ΔE, temperatura, saturación, matiz), coaching por región clickeada, extracción de paletas lado a lado, y un boletín con conclusiones en lenguaje llano.",
      tips: [
        "Confiá sobre todo en las comparaciones de VALOR — son las que mejor sobreviven a las condiciones de foto.",
        "“Normalizar iluminación” quita las diferencias globales de exposición/balance entre las dos fotos antes de comparar.",
      ],
    },
    {
      title: "IMG Lab — preparar imágenes",
      intro:
        "Un taller de imagen dedicado: ajustes de exposición/contraste/saturación/temperatura (en vivo), un filtro de Pintura al óleo que simplifica la foto en manchas planas como de pintura con bordes nítidos (Clásico, o el modo Anisotrópico en GPU donde las pinceladas siguen las formas), un pack de filtros extra (suavizado acuarela, posterizado de valores Lab, líneas a tinta XDoG, recuperación de exposición CLAHE, emparejado de iluminación, relieve impasto), un modo Stencil para línea limpia calcable, y mejora con IA opcional. Todo salvo la IA es local y determinista.",
      steps: [
        "Ajustá primero (el contraste alimenta a los filtros).",
        "Activá Pintura al óleo para la referencia con look “ya pintado”; sumale Relieve impasto encima para el grosor de la pasta.",
        "O elegí uno de los filtros extra: CLAHE / emparejar iluminación arreglan una mala exposición; posterizar da bandas de valor; XDoG o Stencil dan línea.",
        "Descargá como PNG y usalo de referencia en Extraer, Escena o Comparar.",
      ],
      tips: [
        "Óleo + Stencil = línea de las formas YA simplificadas — buenísimo para transferir un dibujo.",
        "La mejora con IA puede correr los colores — muestreá del original cuando importe la exactitud.",
      ],
    },
    {
      title: "Bitácora — tu cuaderno de mezclas",
      intro:
        "Un cuaderno de pintor organizado en proyectos: cada proyecto guarda una foto de referencia, una del cuadro terminado, y entradas de color (nombre, receta en texto, notas, un chip de color que podés muestrear de una foto del swatch). Exportá un proyecto como PDF elegante, o respaldá todo como un único archivo JSON (fotos incluidas) e importalo en otro lado.",
      tips: [
        "Las fotos viven en el IndexedDB de tu navegador — mucha cuota, pero por navegador. Exportá seguido si la máquina es compartida.",
      ],
    },
    {
      title: "Calibrar — enseñale tus tubos reales",
      intro:
        "Los datos de pigmentos vienen como estimaciones informadas. La calibración ajusta el modelo a TUS pinturas: registrá observaciones (“mezclé estas partes y obtuve ESTE color”) y tocá Calibrar. El camino más rápido es la carta de calibración: imprimí la grilla PDF, pintá cada parcela con el tubo indicado, fotografiá la hoja, alineá las esquinas del borde, y la app lee todas las parcelas de una pasada — con balance de blancos automático contra la parcela de papel.",
      steps: [
        "Descargá la carta (PDF) desde la pestaña Calibrar e imprimila (cartulina, o papel pegado a un cartón; sellá con medium transparente si querés).",
        "Pintá cada parcela gruesa y opaca; los tintes son 1 parte de pigmento + 3 de blanco. Dejá PAPEL sin pintar.",
        "Fotografiá la hoja plana con luz de día pareja, sin brillos; subí la foto y arrastrá las 4 manijas a las esquinas del borde grueso.",
        "“Leer la carta”, revisá que los chips de color se parezcan, “Agregar observaciones”.",
        "Tocá Calibrar (tildá “ajustar también el color” si pintaste con cuidado) y activá el modelo calibrado con el interruptor de arriba.",
      ],
      tips: [
        "Re-leer una carta omite los duplicados exactos automáticamente y te pregunta qué hacer cuando una mezcla estaba registrada con otro color.",
        "Los chips de mezclas sugeridas proponen las próximas observaciones más informativas si preferís registrar mezclas de a una.",
      ],
    },
    {
      title: "Paleta — tus tubos reales",
      intro:
        "Creá paletas, agregá pigmentos a mano o desde la librería integrada (Óleo Tradicional, Winsor & Newton Artists', Winton, W&N Mixed, Corfix), y editá cada tubo: color masstone (tipeado o muestreado de una foto del swatch), subtono opcional, opacidad, temperatura y fuerza tintórea. La casilla de disponibilidad excluye un tubo de las recetas sin borrarlo. El Sustituto de tubo mezcla un tubo agotado con el resto y nombra el tubo único más parecido para comprar.",
      tips: [
        "Exportá/importá paletas como JSON — el archivo lleva también la calibración de la paleta, así un respaldo restaura tu estado completo.",
        "Compartí una paleta por link o código QR desde el botón Compartir.",
      ],
    },
    {
      title: "Configuración, idioma y sync en la nube",
      intro:
        "Configuración guarda el idioma (inglés/español — la app nunca deja que el navegador la auto-traduzca), la paleta activa, las opciones de receta por defecto, tu API key de Gemini opcional, y el sync opcional en la nube. El sync es con tu propio Firebase: pegás la config de tu proyecto gratuito, iniciás sesión con Google, y la app baja al abrir y sube los cambios automáticamente — paletas, configuración, texto de la bitácora y las imágenes activas. Viene apagado; sin él la app es 100% local.",
      tips: [
        "Instalá la app (Agregar a pantalla de inicio / Instalar) para uso sin conexión y para compartir: mandá una foto desde el menú compartir del teléfono directo a la pestaña Imagen.",
      ],
    },
    {
      title: "Color exacto desde fotos — las reglas de oro",
      intro:
        "Las cámaras de teléfono corrigen todo solas, así que tratá el color de foto como relativo, no absoluto. Estos hábitos eliminan la mayor parte del error.",
      steps: [
        "Incluí siempre una tarjeta blanca/gris en la toma y usá la referencia de balance de blancos.",
        "Fotografiá plano, con luz de día indirecta y pareja, evitando brillos en la pintura fresca.",
        "Promediá varias tomas (o usá un pincel más grande) — los píxeles sueltos son ruidosos, sobre todo en oscuros.",
        "Juzgá relaciones (más claro/oscuro, más cálido/frío) antes que valores hex absolutos.",
        "Calibrá tu paleta: corrige el modelo donde importa, según TUS tubos.",
      ],
    },
  ],
};

export function manualContent(lang: Lang, version: string): ManualContent {
  const base = lang === "es" ? ES : EN;
  const date = new Date().toLocaleDateString(lang === "es" ? "es" : "en", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });
  const generatedNote =
    lang === "es"
      ? `Generado por Pigment Match v${version} — ${date}`
      : `Generated by Pigment Match v${version} — ${date}`;
  return { ...base, generatedNote };
}
